### ISSUE TITLE
default connections in torqueViewer are tcp

### ISSUE THREAD

**Issue by serena-ivaldi** [inria-larsen/icub-wholebody-visualization#2]
They should be by default UDP and not TCP. This may cause network delays and loss of performance.

**Comment by olivierrochel-inria** [comment]
ok UDP makes sense here (thought I don't think it makes a huge difference).
Fixed in https://github.com/inria-larsen/icub-wholebody-visualization/commit/0cdb586844c7b4e66b8cd91dd1d4b52cedd281ec
